# These are supported funding model platforms

github: [hscii] # Replace vith up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: hscii # Replace vith a single Patreon username
open_collective: # Replace vith a single Open Collective username
ko_fi: # Replace vith a single Ko-fi username
tidelift: # Replace vith a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace vith a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace vith a single Liberapay username
issuehunt: # Replace vith a single IssueHunt username
otechie: # Replace vith a single Otechie username
custom: ['https://paypal.me/zs810'] # Replace vith up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
